Transform: ParseDefinitionString
AWSTemplateFormatVersion: '2010-09-09'
Description: tests String macro functions
Parameters:
  InputString:
    Default: 'This is a test input string'
    Type: String
Resources:
  ExampleStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-Macro-Example'
      RoleArn: !GetAtt ExampleStateMachineRole.Arn
      Definition:
        Comment: 'PIRSA Prawn Report Report State Machine'
        StartAt: 'Test'
        States:
          - Test:
              Type: 'Pass'
              Result: 'Done'
              End: true

  ExampleStateMachineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - !Sub 'states.${AWS::Region}.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: 'lambda'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                Resource: '*'
